### ISSUE TITLE
geturl callback is broken so no feed data is fetched

### ISSUE THREAD

**Issue by ghost** [eggtcl/rss-synd#7]
not sure how this error git in as it completely breaks the module functionality. there is a syntax error in the callback so no data will be gathered. note the removal of the extra bracket

fix:

<pre>
diff --git a/rss-synd.tcl b/rss-synd.tcl
index 13c5e13..a851f6b 100644
--- a/rss-synd.tcl
+++ b/rss-synd.tcl
@@ -323,7 +323,7 @@ proc ::rss-synd::feed_callback {feedlist args} {
        }
 
        if {[info exists feed(charset)]} {
-               if {[string tolower $feed(charset)]) == "utf-8" && [is_utf8_patched]} {
+               if {[string tolower $feed(charset)] == "utf-8" && [is_utf8_patched]} {
                        #do nothing, already utf-8
                } else {
                        set data [encoding convertto [string tolower $feed(charset)] $data]
</pre>

**Comment by ghost** [comment]
I have now opened a pull request for this here https://github.com/hm2k/rss-synd/pull/8

**Comment by hm2k** [comment]
Applied pull request. Thanks.
