### ISSUE TITLE
No longer work with TCL 8.6 and TRF

### ISSUE THREAD

**Issue by Generator** [eggtcl/rss-synd#9]
I'm using Archlinux, after last tcl upgrade (8.5.13 -> 8.6.0), trf no longer work with tcl

<pre><code>RSS Error: Unable to decompress "http://pplware.sapo.pt/feed/": zlib error (decompressor): invalid stored block lengths</code></pre>

trf seems dead, works fine with tcl 8.5, but no longer with tcl 8.6.
Any alternative to trf?!

**Comment by tomek** [comment]
Tcl 8.6 is using build-in zlib for compression so thats why Trf fails, I installed tcl 8.6b2 and I can use both build-in zlib & trf (i've scripts that needs zlib but for sake of rss-synd i installed trf). You can use guide from [here](http://eggwiki.org/Local_Tcl) to locally install tcl & compile eggdrop against it.

**Comment by nik-k** [comment]
Would be nice to have a patch for that problem. Script should check which version of tcl is in use. I will try...

**Comment by thezoggy** [comment]
this fixed it for me on 8.6: http://forum.egghelp.org/viewtopic.php?p=101572#101572

**Comment by PR0r** [comment]
This is broken again for me.. 
RSS Error: Unable to decompress "http://feeds.reuters.com/news/reutersmedia": zlib error 
(decompressor): invalid stored block lengths

When changing rss-synd.tcl with the above fix it produces this error
RSS Error: Unable to decompress "http://feeds.reuters.com/news/reutersmedia": invalid command name " "

Any ideas?
